// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVQnWbcLnZDR81vsWo7FAWrK2li_Gksbo',
    appId: '1:46956409741:web:6862c31cae68d507d503c4',
    messagingSenderId: '46956409741',
    projectId: 'marketplace-d59a5',
    authDomain: 'marketplace-d59a5.firebaseapp.com',
    storageBucket: 'marketplace-d59a5.appspot.com',
    measurementId: 'G-JD8PDPQ33V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT7NesWJb9OCM1jFZLfwq5ytwkuNzb-Xs',
    appId: '1:46956409741:android:1bed8f2a2b0bb9ebd503c4',
    messagingSenderId: '46956409741',
    projectId: 'marketplace-d59a5',
    storageBucket: 'marketplace-d59a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUofDoNm37e3dHDRWns0EiwinX2-tRW4U',
    appId: '1:46956409741:ios:40ecbc0c2de4afb5d503c4',
    messagingSenderId: '46956409741',
    projectId: 'marketplace-d59a5',
    storageBucket: 'marketplace-d59a5.appspot.com',
    iosBundleId: 'com.example.testProgramm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUofDoNm37e3dHDRWns0EiwinX2-tRW4U',
    appId: '1:46956409741:ios:40ecbc0c2de4afb5d503c4',
    messagingSenderId: '46956409741',
    projectId: 'marketplace-d59a5',
    storageBucket: 'marketplace-d59a5.appspot.com',
    iosBundleId: 'com.example.testProgramm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVQnWbcLnZDR81vsWo7FAWrK2li_Gksbo',
    appId: '1:46956409741:web:7192a207cb101f51d503c4',
    messagingSenderId: '46956409741',
    projectId: 'marketplace-d59a5',
    authDomain: 'marketplace-d59a5.firebaseapp.com',
    storageBucket: 'marketplace-d59a5.appspot.com',
    measurementId: 'G-FY8WY0M0N0',
  );
}
